### ISSUE TITLE
Suggestion: Glossary

### ISSUE THREAD

**Issue by cecille** [project-chip/matter-handbook#28]
**Why is this content needed**
It's just nice to have a central location to look up some of the acryonyms and terms we use on a regular basis.

**Who will benifit,**
This would mostly be aimed at developers who are new to Matter.

**Are you able and willing to create the content**
yes, well, a start at least. https://github.com/project-chip/matter-handbook/pull/27

**Additional context**
I don't know how to build the site so I have no idea if those headers are correct or whether it makes sense to have the whole thing in an index. If you add corrections on the PR, I can make the fixes.

**Comment by amolivo** [comment]
approved in PMTT on 11/20. I made some edits to [#27 ](https://github.com/project-chip/matter-handbook/pull/27) and merged it.
